export default {
  BASE_URL_HOLOMOG: "https://flowit-pagcom-homologacao.herokuapp.com/api/v1",
  BASE_URL: "https://flowit-pagcom-staging.herokuapp.com/api/v1",
  BASE_URL__: "https://flowit-pagcom-production.herokuapp.com/api/v1",
  LOGIN: "/sessions",
  PAYMENT_LIST: "/payments.json",
  PAYMENT_FILTER: "/payments/",
  DAILY_DEPOSITS: "/daily_deposits.json",
  DEPOSITS: "/deposits/",
  NEW_PAYMENT: "/payments/",
  BANK_DATA: "/bank_accounts/",
  ANTICIPATE: "/account/anticipations/rule.json",
  ACCOUNTS_UPDATE: "/accounts/update.json",
  RECOVERY: "/passwords/recovery-token",
  RECOVERY_TOKEN: "/passwords/update-by-token",
  DRAWBALANCE: "/wallets/withdraw",
  TRANSFER: "/wallets/qr-transfer",
  TRANSFER_SEND: "/wallets/transfer",
  ACCOUNT_REGISTER: "/accounts",
  EXTRACT: "/wallet-extract",
  GET_BALANCE: "/wallets",
  PAY_LINK: "/paylinks/",
  ACCOUNT_DATA: "/accounts",
  ID_WALL_TOKEN: "",
  ID_WALL_API_MATRIZ: ""
};
